import {
    setUpNetworkRequestMocking,
    tearDownNetworkRequestMocking,
    cleanUpNetworkRequestMocking,
} from "../.."
import {setup} from "jest-json-schema-extended"
import {simpleGraphQLExampleSchemaString} from "../fixtures/simpleGraphQLSchemaString"

beforeEach(() => {
    cleanUpNetworkRequestMocking()
})

beforeAll(() => {
    const persistentAutoGeneratedGraphQLMocks = [
        {
            requestPattern: "https://thisdomaindoesnotexist.com/graphql",
            graphQLSchema: simpleGraphQLExampleSchemaString,
        },
    ]
    setUpNetworkRequestMocking({persistentAutoGeneratedGraphQLMocks})
})

afterAll(() => {
    tearDownNetworkRequestMocking()
})

setup()
